repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: uv run ruff check . --no-cache
        language: system
        pass_filenames: false
      - id: pyright
        name: Pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
